apiVersion: v1
kind: Service
metadata:
  name: instance-monitoring
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: instance-monitoring
  ports:
    - name: ingest
      port: 5700
      targetPort: 5700
    - name: dashboard
      port: 5701
      targetPort: 5701
