{{- $externalSecret := (lookup "v1" "Secret" .Release.Namespace .Values.global.secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ if $externalSecret }}{{ index $externalSecret.data "POSTGRES_USER" | b64dec }}{{ else }}changeUser{{ end }}
  POSTGRES_PASSWORD: {{ if $externalSecret }}{{ index $externalSecret.data "POSTGRES_PASSWORD" | b64dec }}{{ else }}changePassword{{ end }}
  POSTGRES_DB: {{ if $externalSecret }}{{ index $externalSecret.data "POSTGRES_DB" | b64dec | default "n8n" }}{{ else }}n8n{{ end }}
  POSTGRES_NON_ROOT_USER: {{ if $externalSecret }}{{ index $externalSecret.data "POSTGRES_NON_ROOT_USER" | b64dec }}{{ else }}changeUser{{ end }}
  POSTGRES_NON_ROOT_PASSWORD: {{ if $externalSecret }}{{ index $externalSecret.data "POSTGRES_NON_ROOT_PASSWORD" | b64dec }}{{ else }}changePassword{{ end }}