apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: {{ .Values.pvc.label | default "n8n-claim0" }}
  name: {{ .Values.pvc.name | default "n8n-claim0" }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "2Gi" }}
