apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.postgresService.selector.service }}
  name: {{ .Values.postgresService.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  clusterIP: {{ .Values.postgresService.clusterIP }}
  ports:
    - name: "{{ .Values.postgresService.port }}"
      port: {{ .Values.postgresService.port }}
      targetPort: {{ .Values.postgresService.targetPort }}
      protocol: {{ .Values.postgresService.protocol }}
  selector:
    service: {{ .Values.postgresService.selector.service }}
