apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.postgresSecret.name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresSecret.user }}
  POSTGRES_PASSWORD: {{ .Values.postgresSecret.password }}
  POSTGRES_DB: {{ .Values.postgresSecret.db }}
  POSTGRES_NON_ROOT_USER: {{ .Values.postgresSecret.nonRootUser }}
  POSTGRES_NON_ROOT_PASSWORD: {{ .Values.postgresSecret.nonRootPassword }}