{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- $saAnns := dict }}
  {{- if and .Values.s3.enabled .Values.s3.auth.autoDetect .Values.serviceAccount.awsRoleArn }}
  {{- $_ := set $saAnns "eks.amazonaws.com/role-arn" .Values.serviceAccount.awsRoleArn }}
  {{- end }}
  {{- $merged := merge (deepCopy (.Values.serviceAccount.annotations | default dict)) $saAnns (.Values.commonAnnotations | default dict) }}
  {{- with $merged }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
