apiVersion: v1
kind: ConfigMap
metadata:
  name: init-data
  namespace: n8n
data:
  init-data.sh: |
    #!/bin/bash
    set -e;
    if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
    	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
    		-v n8n_user="$POSTGRES_NON_ROOT_USER" -v n8n_password="$POSTGRES_NON_ROOT_PASSWORD" -v n8n_db="$POSTGRES_DB" <<-'EOSQL'
    		SELECT format('CREATE USER %I', :'n8n_user') WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'n8n_user') \gexec
    		SELECT format('ALTER ROLE %I WITH LOGIN PASSWORD %L', :'n8n_user', :'n8n_password') \gexec
    		SELECT format('GRANT ALL PRIVILEGES ON DATABASE %I TO %I', :'n8n_db', :'n8n_user') \gexec
    		SELECT format('GRANT ALL ON SCHEMA public TO %I', :'n8n_user') \gexec
    	EOSQL
    else
    	echo "SETUP INFO: No Environment variables given!"
    fi
