apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n-demo
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: standard
  POSTGRES_NON_ROOT_PASSWORD: standard