apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: n8n-pvc
  name: n8n-pvc
  namespace: n8n

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 2Gi
